name: Build Jupyter Book

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  # Replace with the actual path to your requirements file, if applicable

      - name: Build Jupyter Book
        run: |
          jupyter-book build .
